#pragma once

#include "terminal.h"

enum
{
	XGA_COLOR_BLACK = 0,
	XGA_COLOR_BLUE = 1,
	XGA_COLOR_GREEN = 2,
	XGA_COLOR_CYAN = 3,
	XGA_COLOR_RED = 4,
	XGA_COLOR_MAGENTA = 5,
	XGA_COLOR_BROWN = 6,
	XGA_COLOR_LIGHT_GREY = 7,
	XGA_COLOR_DARK_GREY = 8,
	XGA_COLOR_LIGHT_BLUE = 9,
	XGA_COLOR_LIGHT_GREEN = 10,
	XGA_COLOR_LIGHT_CYAN = 11,
	XGA_COLOR_LIGHT_RED = 12,
	XGA_COLOR_LIGHT_MAGENTA = 13,
	XGA_COLOR_LIGHT_BROWN = 14,
	XGA_COLOR_WHITE = 15,
};

void vgaterminal_setup(terminal_t* terminal);